// 카드 데이터
// 기본 카드: [이모지, 한국어, English, 한국어 소리/설명, English sound]
// type "color": 6번째 값 = 색상(hex 또는 "rainbow"/"gold"), 이모지는 예시 사물
// type "shape": 첫 값 = 도형 키 (app.js의 SHAPES 참고)
// type "number": 6번째 값 = 개수, 이모지는 세는 사물
window.CATEGORIES = [
  { id: "animals", names: ["동물", "Animals"], cover: "🐰", color: "#ffd6e7", cards: [
    ["🐶","강아지","Dog","멍멍! 꼬리를 흔들어요.","Woof, woof!"],
    ["🐱","고양이","Cat","야옹~ 야옹~","Meow, meow!"],
    ["🐰","토끼","Rabbit","깡충깡충 뛰어요!","Hop, hop, hop!"],
    ["🐭","쥐","Mouse","찍찍! 찍찍!","Squeak, squeak!"],
    ["🐷","돼지","Pig","꿀꿀! 꿀꿀!","Oink, oink!"],
    ["🐮","소","Cow","음매~","Moo!"],
    ["🐴","말","Horse","히이잉! 다그닥 다그닥!","Neigh!"],
    ["🐑","양","Sheep","메에~ 메에~","Baa, baa!"],
    ["🐔","닭","Chicken","꼬끼오!","Cock-a-doodle-doo!"],
    ["🐥","병아리","Chick","삐약삐약!","Cheep, cheep!"],
    ["🦆","오리","Duck","꽥꽥! 꽥꽥!","Quack, quack!"],
    ["🐸","개구리","Frog","개굴개굴!","Ribbit, ribbit!"],
    ["🦁","사자","Lion","어흥! 사자가 울어요.","Roar!"],
    ["🐯","호랑이","Tiger","어흥! 줄무늬 호랑이!","Grrr!"],
    ["🐻","곰","Bear","으르렁! 곰이에요.","Growl!"],
    ["🐼","판다","Panda","대나무를 냠냠 먹어요.","Munch, munch!"],
    ["🐨","코알라","Koala","나무를 꼭 안아요.","Hug the tree!"],
    ["🐵","원숭이","Monkey","우끼끼! 우끼끼!","Ooh ooh, ah ah!"],
    ["🐘","코끼리","Elephant","뿌우~ 코가 길어요.","Toot! Long trunk!"],
    ["🦒","기린","Giraffe","목이 아주 길어요.","A very long neck!"],
    ["🦓","얼룩말","Zebra","까만 줄, 하얀 줄!","Black and white stripes!"],
    ["🦊","여우","Fox","살금살금 걸어요.","Sneak, sneak!"],
    ["🦉","부엉이","Owl","부엉부엉!","Hoo, hoo!"],
    ["🐧","펭귄","Penguin","뒤뚱뒤뚱 걸어요.","Waddle, waddle!"],
    ["🦩","플라밍고","Flamingo","분홍색 새예요!","A pink bird!"],
    ["🦜","앵무새","Parrot","안녕! 말을 따라 해요.","Hello! Hello!"],
    ["🐿️","다람쥐","Squirrel","도토리를 좋아해요.","It loves acorns!"],
    ["🦔","고슴도치","Hedgehog","가시가 뾰족뾰족!","Spiky, spiky!"]
  ]},
  { id: "princess", names: ["공주 놀이", "Princess Play"], cover: "👸", color: "#ffc4e1", cards: [
    ["👸","공주","Princess","예쁜 공주님이에요.","A pretty princess!"],
    ["🤴","왕자","Prince","멋진 왕자님이에요.","A brave prince!"],
    ["👑","왕관","Crown","반짝반짝 왕관!","A shiny crown!"],
    ["🏰","성","Castle","공주님이 사는 성이에요.","The princess lives here!"],
    ["🦄","유니콘","Unicorn","뿔이 하나 있어요.","It has one horn!"],
    ["🧚","요정","Fairy","날개로 훨훨 날아요.","Flutter, flutter!"],
    ["🧜‍♀️","인어공주","Mermaid","바닷속에서 헤엄쳐요.","She swims in the sea!"],
    ["🪄","요술봉","Magic Wand","얍! 반짝반짝 마법!","Abracadabra!"],
    ["💎","보석","Jewel","반짝반짝 빛나요.","Sparkle, sparkle!"],
    ["💍","반지","Ring","손가락에 쏙!","On my finger!"],
    ["🎀","리본","Ribbon","머리에 리본을 달아요.","A bow for my hair!"],
    ["👗","드레스","Dress","빙글빙글 돌아요.","Twirl, twirl!"],
    ["👠","구두","High Heels","또각또각!","Click, clack!"],
    ["🪞","거울","Mirror","거울아, 거울아!","Mirror, mirror!"],
    ["🦢","백조","Swan","우아하게 헤엄쳐요.","A graceful swan!"],
    ["🐉","용","Dragon","불을 후~ 뿜어요.","Whoosh, fire!"],
    ["🫖","찻주전자","Teapot","차를 쪼르륵!","Pour the tea!"],
    ["💖","반짝 하트","Sparkling Heart","사랑해요!","I love you!"]
  ]},
  { id: "fruits", names: ["과일", "Fruits"], cover: "🍓", color: "#ffd0d6", cards: [
    ["🍎","사과","Apple","빨갛고 아삭아삭!","Red and crunchy!"],
    ["🍏","청사과","Green Apple","초록색 사과예요.","A green apple!"],
    ["🍌","바나나","Banana","노랗고 길쭉해요.","Long and yellow!"],
    ["🍓","딸기","Strawberry","새콤달콤 딸기!","Sweet strawberry!"],
    ["🍉","수박","Watermelon","시원하고 달아요.","Cool and juicy!"],
    ["🍇","포도","Grapes","포도알이 송알송알!","A bunch of grapes!"],
    ["🍊","귤","Tangerine","껍질을 까서 먹어요.","Peel and eat!"],
    ["🍑","복숭아","Peach","말랑말랑 복숭아!","Soft and fuzzy!"],
    ["🍒","체리","Cherries","동글동글 두 개!","Two round cherries!"],
    ["🥝","키위","Kiwi","속이 초록색이에요.","Green inside!"],
    ["🍍","파인애플","Pineapple","머리가 뾰족뾰족!","Spiky on top!"],
    ["🥭","망고","Mango","노랗고 달콤해요.","Sweet and yellow!"],
    ["🍋","레몬","Lemon","아이, 셔!","So sour!"],
    ["🫐","블루베리","Blueberries","작고 동그래요.","Tiny and round!"],
    ["🍈","멜론","Melon","향긋한 멜론!","Sweet melon!"],
    ["🍅","토마토","Tomato","빨갛고 동그래요.","Red and round!"],
    ["🥥","코코넛","Coconut","껍질이 딱딱해요.","A hard shell!"],
    ["🥑","아보카도","Avocado","가운데 씨가 커요.","A big seed inside!"]
  ]},
  { id: "food", names: ["음식", "Food"], cover: "🧁", color: "#ffe2c6", cards: [
    ["🍚","밥","Rice","냠냠 밥을 먹어요.","Yummy rice!"],
    ["🍙","주먹밥","Rice Ball","동글동글 주먹밥!","A round rice ball!"],
    ["🍞","빵","Bread","폭신폭신 빵!","Soft bread!"],
    ["🥚","달걀","Egg","동그란 달걀이에요.","An egg!"],
    ["🍳","달걀프라이","Fried Egg","지글지글!","Sizzle, sizzle!"],
    ["🍜","국수","Noodles","후루룩 후루룩!","Slurp, slurp!"],
    ["🍕","피자","Pizza","치즈가 쭈욱!","Cheesy pizza!"],
    ["🍔","햄버거","Hamburger","한입 크게 앙!","A big bite!"],
    ["🍗","닭다리","Chicken Leg","냠냠 맛있어요.","Yummy chicken!"],
    ["🧀","치즈","Cheese","노란 치즈!","Yellow cheese!"],
    ["🥕","당근","Carrot","아삭아삭 당근!","Crunchy carrot!"],
    ["🥦","브로콜리","Broccoli","작은 나무 같아요.","Like a tiny tree!"],
    ["🌽","옥수수","Corn","알이 톡톡!","Pop, pop!"],
    ["🥔","감자","Potato","포슬포슬 감자!","A potato!"],
    ["🍠","고구마","Sweet Potato","달콤한 고구마!","A sweet potato!"],
    ["🥛","우유","Milk","꿀꺽꿀꺽 마셔요.","Gulp, gulp!"],
    ["🍪","쿠키","Cookie","바삭바삭!","Crunchy cookie!"],
    ["🍩","도넛","Donut","가운데 구멍이 있어요.","A hole in the middle!"],
    ["🧁","컵케이크","Cupcake","크림이 달콤해요.","Sweet and creamy!"],
    ["🎂","케이크","Cake","생일 축하해요!","Happy birthday!"],
    ["🍦","아이스크림","Ice Cream","차갑고 달콤해요.","Cold and sweet!"],
    ["🍭","사탕","Lollipop","알록달록 사탕!","A colorful lollipop!"],
    ["🥞","팬케이크","Pancakes","차곡차곡 쌓아요.","A stack of pancakes!"]
  ]},
  { id: "toys", names: ["장난감", "Toys"], cover: "🧸", color: "#e6d6ff", cards: [
    ["🧸","곰인형","Teddy Bear","꼭 안아 줘요.","A big hug!"],
    ["🎈","풍선","Balloon","두둥실 날아가요.","Float away!"],
    ["⚽","공","Ball","뻥! 공을 차요.","Kick the ball!"],
    ["🪁","연","Kite","하늘 높이 날아요.","Up in the sky!"],
    ["🧩","퍼즐","Puzzle","딱! 맞췄어요.","It fits!"],
    ["🖍️","크레파스","Crayon","쓱쓱 그려요.","Draw, draw!"],
    ["🎨","물감","Paints","알록달록 칠해요.","Paint, paint!"],
    ["🥁","북","Drum","둥둥둥!","Boom, boom!"],
    ["🎹","피아노","Piano","도레미파솔!","Do re mi!"],
    ["🎺","나팔","Trumpet","빠빠빠~","Toot, toot!"],
    ["🎸","기타","Guitar","띵띵띵!","Strum, strum!"],
    ["🪀","요요","Yo-yo","올라갔다 내려와요.","Up and down!"],
    ["🛝","미끄럼틀","Slide","슈웅~ 내려가요!","Whee!"],
    ["🎠","회전목마","Carousel","빙글빙글 돌아요.","Round and round!"],
    ["🎡","관람차","Ferris Wheel","높이 높이 올라가요.","Up so high!"],
    ["🫧","비눗방울","Bubbles","후~ 불면 퐁퐁!","Pop, pop!"],
    ["🎁","선물","Present","짠! 선물이에요.","A present for you!"],
    ["📚","책","Books","책을 읽어요.","Let's read!"],
    ["🪆","인형","Nesting Doll","인형 속에 또 인형!","A doll inside a doll!"]
  ]},
  { id: "vehicles", names: ["탈것", "Vehicles"], cover: "🚗", color: "#cfe9ff", cards: [
    ["🚗","자동차","Car","부릉부릉!","Vroom, vroom!"],
    ["🚌","버스","Bus","빵빵! 버스가 와요.","Beep, beep!"],
    ["🚕","택시","Taxi","택시 타고 가요.","Taxi, taxi!"],
    ["🚒","소방차","Fire Engine","애앵애앵! 불을 꺼요.","Wee-woo!"],
    ["🚑","구급차","Ambulance","삐뽀삐뽀!","Nee-naw!"],
    ["🚓","경찰차","Police Car","삐용삐용!","Wee-oo!"],
    ["🚚","트럭","Truck","짐을 싣고 가요.","Rumble, rumble!"],
    ["🚜","트랙터","Tractor","밭에서 일해요.","Chug, chug!"],
    ["🏎️","경주용 자동차","Race Car","쌩쌩 달려요!","Zoom!"],
    ["🏍️","오토바이","Motorcycle","부아앙!","Vroom!"],
    ["🚲","자전거","Bicycle","따르릉 따르릉!","Ring, ring!"],
    ["🛴","킥보드","Scooter","씽씽 달려요.","Zoom, zoom!"],
    ["🚂","기차","Train","칙칙폭폭!","Choo, choo!"],
    ["🚇","지하철","Subway","땅속으로 달려요.","Under the ground!"],
    ["✈️","비행기","Airplane","슈웅~ 하늘을 날아요.","Whoosh!"],
    ["🚁","헬리콥터","Helicopter","두두두두!","Whirr, whirr!"],
    ["🚀","로켓","Rocket","3, 2, 1, 발사!","Blast off!"],
    ["🚢","배","Ship","뿌우~ 바다를 가요.","Toot, toot!"],
    ["⛵","요트","Sailboat","바람 타고 둥실둥실.","Sail away!"]
  ]},
  { id: "sea", names: ["바다 친구", "Sea"], cover: "🐬", color: "#c9f1f5", cards: [
    ["🐬","돌고래","Dolphin","끼익! 점프해요.","Splash! Jump!"],
    ["🐳","고래","Whale","푸우~ 물을 뿜어요.","Whoosh! Water spout!"],
    ["🦈","상어","Shark","뾰족한 지느러미!","A big fin!"],
    ["🐟","물고기","Fish","뻐끔뻐끔!","Blub, blub!"],
    ["🐠","열대어","Tropical Fish","알록달록 물고기!","A colorful fish!"],
    ["🐡","복어","Pufferfish","빵빵하게 부풀어요.","Puff, puff!"],
    ["🐙","문어","Octopus","다리가 여덟 개!","Eight arms!"],
    ["🦑","오징어","Squid","쓩쓩 헤엄쳐요.","Swish, swish!"],
    ["🦀","게","Crab","옆으로 걸어요.","Walks sideways!"],
    ["🦞","바닷가재","Lobster","집게가 커요.","Big claws!"],
    ["🦐","새우","Shrimp","허리가 구부러졌어요.","A curly shrimp!"],
    ["🪼","해파리","Jellyfish","둥실둥실 떠다녀요.","Float, float!"],
    ["🐢","거북이","Turtle","느릿느릿 헤엄쳐요.","Slow and steady!"],
    ["🦭","물범","Seal","바위에서 쉬어요.","A happy seal!"],
    ["🦦","수달","Otter","물에서 놀아요.","A playful otter!"],
    ["🐚","소라","Seashell","귀에 대면 바닷소리!","Listen to the sea!"],
    ["🪸","산호","Coral","바닷속 꽃 같아요.","Pretty coral!"]
  ]},
  { id: "bugs", names: ["곤충", "Bugs"], cover: "🦋", color: "#fff0b8", cards: [
    ["🦋","나비","Butterfly","팔랑팔랑 날아요.","Flutter, flutter!"],
    ["🐞","무당벌레","Ladybug","빨간 옷에 까만 점!","Red with black spots!"],
    ["🐝","꿀벌","Honeybee","윙윙~ 꿀을 모아요.","Buzz, buzz!"],
    ["🐛","애벌레","Caterpillar","꼬물꼬물 기어가요.","Wiggle, wiggle!"],
    ["🐜","개미","Ant","영차영차 줄지어 가요.","March, march!"],
    ["🐌","달팽이","Snail","느릿느릿 집을 메고 가요.","Slow, slow snail!"],
    ["🦗","귀뚜라미","Cricket","귀뚤귀뚤!","Chirp, chirp!"],
    ["🪲","딱정벌레","Beetle","등이 반짝반짝!","A shiny beetle!"],
    ["🕷️","거미","Spider","거미줄을 만들어요.","It spins a web!"],
    ["🪱","지렁이","Worm","흙 속에서 꿈틀꿈틀!","Wiggly worm!"],
    ["🪰","파리","Fly","윙윙 날아다녀요.","Buzz, fly!"]
  ]},
  { id: "dinos", names: ["공룡", "Dinosaurs"], cover: "🦖", color: "#d5f5c8", cards: [
    ["🦖","티라노사우루스","T. rex","크아앙! 이빨이 뾰족해요.","Roar! Sharp teeth!"],
    ["🦕","목긴 공룡","Long-Neck Dino","목이 아주 길어요.","A very long neck!"],
    ["🥚","공룡 알","Dinosaur Egg","톡톡! 아기 공룡이 나와요.","Crack! A baby dino!"],
    ["🦴","공룡 뼈","Dinosaur Bone","아주 오래된 뼈예요.","A very old bone!"],
    ["🌋","화산","Volcano","부글부글 쾅!","Rumble, boom!"],
    ["🐊","악어","Crocodile","입이 쩍! 커요.","Snap, snap!"],
    ["🦎","도마뱀","Lizard","살금살금 기어가요.","Creep, creep!"],
    ["🐍","뱀","Snake","쉬익쉬익!","Hiss, hiss!"],
    ["🐢","거북이","Turtle","등껍질이 단단해요.","A hard shell!"]
  ]},
  { id: "nature", names: ["자연", "Nature"], cover: "🌸", color: "#ffe0cc", cards: [
    ["☀️","해","Sun","쨍쨍 따뜻해요.","Warm and bright!"],
    ["🌙","달","Moon","밤에 떠요.","Good night, moon!"],
    ["⭐","별","Star","반짝반짝 작은 별!","Twinkle, twinkle!"],
    ["🌈","무지개","Rainbow","일곱 빛깔 무지개!","So many colors!"],
    ["☁️","구름","Cloud","폭신폭신 둥실둥실.","Fluffy cloud!"],
    ["🌧️","비","Rain","주룩주룩!","Pitter-patter!"],
    ["⚡","번개","Lightning","번쩍! 우르릉 쾅!","Flash! Boom!"],
    ["❄️","눈송이","Snowflake","하얀 눈이 펑펑!","Snow is falling!"],
    ["⛄","눈사람","Snowman","눈으로 만들어요.","Made of snow!"],
    ["🌳","나무","Tree","쑥쑥 자라요.","Grow, grow!"],
    ["🌷","튤립","Tulip","봄에 피는 꽃이에요.","A spring flower!"],
    ["🌹","장미","Rose","향기가 좋아요.","It smells nice!"],
    ["🌻","해바라기","Sunflower","해님을 바라봐요.","It looks at the sun!"],
    ["🌸","벚꽃","Cherry Blossom","분홍 꽃잎이 살랑살랑.","Pink petals!"],
    ["🍀","네잎클로버","Four-Leaf Clover","행운의 클로버!","Good luck!"],
    ["🍂","낙엽","Fallen Leaves","바스락바스락!","Crunch, crunch!"],
    ["🌵","선인장","Cactus","가시가 뾰족뾰족!","Prickly!"],
    ["🍄","버섯","Mushroom","우산처럼 생겼어요.","Like an umbrella!"],
    ["⛰️","산","Mountain","높고 높은 산!","A tall mountain!"],
    ["🌊","파도","Wave","철썩철썩!","Splash, splash!"]
  ]},
  { id: "colors", type: "color", names: ["색깔", "Colors"], cover: "🎨", color: "#f1e4ff", cards: [
    ["🍎","빨간색","Red","사과처럼 빨개요.","Red like an apple!","#ff4d5e"],
    ["🍊","주황색","Orange","귤처럼 주황색!","Orange like a tangerine!","#ff9a3c"],
    ["🍌","노란색","Yellow","바나나처럼 노래요.","Yellow like a banana!","#ffd43b"],
    ["🐸","초록색","Green","개구리처럼 초록색!","Green like a frog!","#46c26e"],
    ["🐳","파란색","Blue","고래처럼 파래요.","Blue like a whale!","#3d86f5"],
    ["🍇","보라색","Purple","포도처럼 보라색!","Purple like grapes!","#9a5cf0"],
    ["🌸","분홍색","Pink","벚꽃처럼 분홍색!","Pink like a blossom!","#ff82b8"],
    ["💧","하늘색","Sky Blue","물방울처럼 하늘색!","Light blue like water!","#7fd3ff"],
    ["🐻","갈색","Brown","곰처럼 갈색!","Brown like a bear!","#a2663d"],
    ["⛄","하얀색","White","눈사람처럼 하얘요.","White like a snowman!","#ffffff"],
    ["🐘","회색","Gray","코끼리처럼 회색!","Gray like an elephant!","#9aa3ad"],
    ["🎱","검은색","Black","까만 공이에요.","Black like this ball!","#2f3037"],
    ["👑","금색","Gold","왕관처럼 반짝반짝!","Shiny like a crown!","gold"],
    ["🌈","무지개색","Rainbow","여러 가지 색이 있어요.","All the colors!","rainbow"]
  ]},
  { id: "shapes", type: "shape", names: ["모양", "Shapes"], cover: "🔷", color: "#dcecff", cards: [
    ["circle","동그라미","Circle","동글동글 동그라미!","Round, round circle!"],
    ["triangle","세모","Triangle","뾰족한 곳이 세 개!","Three corners!"],
    ["square","네모","Square","네 변이 똑같아요.","Four equal sides!"],
    ["rectangle","직사각형","Rectangle","길쭉한 네모!","A long box shape!"],
    ["star","별","Star","반짝반짝 별 모양!","Twinkle star!"],
    ["heart","하트","Heart","사랑해요!","I love you!"],
    ["oval","타원","Oval","달걀 모양이에요.","Like an egg!"],
    ["diamond","마름모","Diamond","연 모양 같아요.","Like a kite!"],
    ["crescent","초승달","Crescent","손톱 같은 달 모양!","A thin moon!"],
    ["pentagon","오각형","Pentagon","뾰족한 곳이 다섯 개!","Five corners!"],
    ["hexagon","육각형","Hexagon","벌집 모양이에요.","Like a honeycomb!"]
  ]},
  { id: "numbers", type: "number", names: ["숫자", "Numbers"], cover: "🔢", color: "#d8f5e4", cards: [
    ["🍎","하나","One","사과 하나!","One apple!",1],
    ["🐰","둘","Two","토끼 둘!","Two bunnies!",2],
    ["🍓","셋","Three","딸기 셋!","Three strawberries!",3],
    ["🐥","넷","Four","병아리 넷!","Four chicks!",4],
    ["⭐","다섯","Five","별 다섯!","Five stars!",5],
    ["🌷","여섯","Six","튤립 여섯!","Six tulips!",6],
    ["🎈","일곱","Seven","풍선 일곱!","Seven balloons!",7],
    ["🐞","여덟","Eight","무당벌레 여덟!","Eight ladybugs!",8],
    ["🧁","아홉","Nine","컵케이크 아홉!","Nine cupcakes!",9],
    ["🍭","열","Ten","사탕 열!","Ten lollipops!",10]
  ]},
  { id: "body", names: ["내 몸", "My Body"], cover: "👶", color: "#ffdcd2", cards: [
    ["😊","얼굴","Face","방긋 웃는 얼굴!","A smiling face!"],
    ["👀","눈","Eyes","깜빡깜빡!","Blink, blink!"],
    ["👂","귀","Ear","소리를 들어요.","I can hear!"],
    ["👃","코","Nose","킁킁 냄새를 맡아요.","Sniff, sniff!"],
    ["👄","입","Mouth","아~ 하고 벌려요.","Open wide!"],
    ["🦷","이","Tooth","치카치카 닦아요.","Brush, brush!"],
    ["👅","혀","Tongue","메롱!","Blah!"],
    ["👋","손","Hand","안녕~ 흔들어요.","Wave hello!"],
    ["👍","엄지","Thumb","최고예요!","Thumbs up!"],
    ["💪","팔","Arm","힘이 세요!","So strong!"],
    ["🦵","다리","Leg","성큼성큼 걸어요.","Step, step!"],
    ["🦶","발","Foot","쿵쿵 굴러요.","Stomp, stomp!"],
    ["👶","아기","Baby","응애응애!","Waa, waa!"]
  ]},
  { id: "home", names: ["우리 집", "At Home"], cover: "🏠", color: "#d9f2e6", cards: [
    ["🏠","집","House","우리 집이에요.","Home sweet home!"],
    ["🚪","문","Door","똑똑! 누구세요?","Knock, knock!"],
    ["🪟","창문","Window","밖을 봐요.","Look outside!"],
    ["🛏️","침대","Bed","쿨쿨 자요.","Sleep tight!"],
    ["🛋️","소파","Sofa","폭신폭신 앉아요.","Soft and comfy!"],
    ["🪑","의자","Chair","의자에 앉아요.","Sit down!"],
    ["📺","텔레비전","TV","짜잔! 화면이 켜져요.","TV time!"],
    ["⏰","시계","Clock","똑딱똑딱!","Tick, tock!"],
    ["💡","전구","Light Bulb","반짝! 불이 켜져요.","Light on!"],
    ["🛁","욕조","Bathtub","첨벙첨벙 목욕해요.","Splash, splash!"],
    ["🚽","변기","Toilet","쉬~ 하고 물을 내려요.","Flush!"],
    ["🧼","비누","Soap","뽀득뽀득 손을 씻어요.","Wash, wash!"],
    ["🪥","칫솔","Toothbrush","치카치카!","Brush, brush!"],
    ["🥄","숟가락","Spoon","숟가락으로 냠냠.","Scoop, scoop!"],
    ["🥢","젓가락","Chopsticks","콕콕 집어요.","Pick it up!"],
    ["🧦","양말","Socks","쏙쏙 신어요.","Socks on!"],
    ["👕","티셔츠","T-shirt","옷을 입어요.","Get dressed!"],
    ["👟","운동화","Sneakers","신발 신고 나가요.","Let's go out!"],
    ["🧢","모자","Cap","머리에 써요.","On my head!"],
    ["☂️","우산","Umbrella","비가 오면 펼쳐요.","Open it in the rain!"],
    ["🎒","가방","Backpack","어린이집 가요.","Off to school!"]
  ]},
  { id: "jobs", names: ["직업", "Jobs"], cover: "🧑‍🚒", color: "#ffe6c9", cards: [
    ["🧑‍🚒","소방관","Firefighter","불을 꺼 줘요.","Puts out fires!"],
    ["👮","경찰관","Police Officer","우리를 지켜 줘요.","Keeps us safe!"],
    ["🧑‍⚕️","의사","Doctor","아픈 곳을 고쳐 줘요.","Helps us get well!"],
    ["🧑‍🍳","요리사","Chef","맛있는 요리를 해요.","Cooks yummy food!"],
    ["🧑‍🏫","선생님","Teacher","친절하게 가르쳐 줘요.","Teaches us!"],
    ["🧑‍🌾","농부","Farmer","채소를 길러요.","Grows vegetables!"],
    ["👷","공사 일꾼","Builder","뚝딱뚝딱 지어요.","Builds things!"],
    ["🧑‍🔧","정비사","Mechanic","자동차를 고쳐요.","Fixes cars!"],
    ["🧑‍🔬","과학자","Scientist","신기한 실험을 해요.","Does experiments!"],
    ["🧑‍🚀","우주비행사","Astronaut","우주로 날아가요.","Flies to space!"],
    ["🧑‍✈️","조종사","Pilot","비행기를 운전해요.","Flies the plane!"],
    ["🧑‍🎨","화가","Artist","그림을 그려요.","Paints pictures!"],
    ["🧑‍🎤","가수","Singer","랄랄라 노래해요.","La la la!"]
  ]},
  { id: "feelings", names: ["마음", "Feelings"], cover: "🥰", color: "#ffd9ef", cards: [
    ["😊","기뻐요","Happy","방긋방긋 웃어요.","Big smile!"],
    ["😆","신나요","Excited","야호! 신나요!","Yay!"],
    ["🥰","사랑해요","Loving","하트가 뿅뿅!","Love, love!"],
    ["😍","좋아요","I Like It","눈에 하트가 생겼어요.","Heart eyes!"],
    ["😋","맛있어요","Yummy","냠냠 맛있어요.","Yum, yum!"],
    ["🥳","축하해요","Celebrating","짝짝짝 축하해요!","Hooray!"],
    ["🤗","안아 줘요","Hug","꼬옥 안아 줘요.","Big hug!"],
    ["😌","편안해요","Calm","후~ 숨을 쉬어요.","Breathe in, breathe out."],
    ["🤔","궁금해요","Curious","음~ 뭘까?","Hmm, what is it?"],
    ["😮","놀라요","Surprised","우와! 깜짝이야!","Wow!"],
    ["😳","부끄러워요","Shy","얼굴이 빨개져요.","A little shy."],
    ["😴","졸려요","Sleepy","하암~ 졸려요.","Yawn!"],
    ["😢","슬퍼요","Sad","눈물이 또르르.","A little tear."],
    ["😭","엉엉 울어요","Crying","엉엉 울어요.","Boo hoo!"],
    ["😠","화나요","Angry","씩씩 화가 나요.","Grr, angry!"],
    ["😨","무서워요","Scared","무서워요, 안아 줘요.","Scared! Hug me!"],
    ["🤒","아파요","Sick","열이 나요.","I feel sick."]
  ]}
];
